name: Publish Package to npmjs
on:
  push:
    branches:
      - main
concurrency:
  group: ${{github.repository}}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Publish to npm
        run: |
          yarn install --immutable
          yarn npm publish --access public --tolerate-republish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
